# -*- coding: utf-8 -*-
"""v2 panel 列族分组表（冻结物 `docs/data/v2_p1_build_freeze.md` §2/§6 的代码单一来源）。

由 `temp/p1_column_groups_20261002.json`（383 列 → 8 panel 族 + labels，已校验全覆盖、
无重复、无遗漏）一次性固化为代码常量——JSON 只是生成中间物，**不是运行时依赖**。

- PANEL_GROUPS：8 族共 377 列（core 52 / fundamental 69 / moneyflow 44 / technical 43 /
  announcement 10 / risk 29 / market_state 13 / neutralized 117），announcement 不含物化列；
- MATERIALIZED_DERIVED：冻结 §6 物化拍板的 34 列运行时派生（ht 10 + rp 6 + tfh 8 +
  ti 6 + has 4），全部进 announcement 族，manifest 登记 status="deprecated"；
- LABEL_TABLES：3 张标签表（label 值列, neu 变体列），labels 独立成表不是 panel 族。
"""

from __future__ import annotations

__all__ = [
    "PANEL_GROUPS",
    "MATERIALIZED_DERIVED",
    "LABEL_TABLES",
    "LABEL_VALUE_COLUMNS",
    "ARCHIVE_HOT_BOUNDARY",
    "group_of_column",
    "columns_of_group",
    "validate_mapping",
]

#: 冷热分层边界（冻结 §3）：<= 该日落冷区月分区，> 该日落热区日分区（热区 2025-07 起）
ARCHIVE_HOT_BOUNDARY = "20250630"

#: 8 panel 族 → 列清单（冻结 §2 附录 A 逐项一致）
PANEL_GROUPS: dict[str, tuple[str, ...]] = {
    "core": (
        "amount",
        "amount_ma10",
        "amount_ma20",
        "amount_ma5",
        "bp",
        "circ_mv",
        "dv_ttm",
        "dv_ttm_missing",
        "ep_ttm",
        "in_date",
        "intraday_vol_structure",
        "is_limit_down",
        "is_limit_up",
        "is_loss",
        "is_st",
        "is_suspended",
        "list_days",
        "log_circ_mv",
        "log_total_mv",
        "ma_deviation_10",
        "ma_deviation_20",
        "ma_deviation_5",
        "opening_strength",
        "pb",
        "pe_ttm",
        "pe_ttm_missing",
        "ps_ttm",
        "ret_1",
        "ret_10",
        "ret_20",
        "ret_5",
        "sw_industry",
        "sw_industry_code",
        "sw_industry_id",
        "sw_l1",
        "sw_l1_code",
        "sw_l1_id",
        "sw_l2",
        "sw_l2_code",
        "sw_l2_id",
        "sw_l3",
        "sw_l3_code",
        "total_mv",
        "tradable",
        "trade_date",
        "ts_code",
        "turnover_rate",
        "vol",
        "vol_ratio_10",
        "vol_ratio_20",
        "vol_ratio_5",
        "volume_ratio",
    ),
    "fundamental": (
        "assets_turn",
        "capex_to_ocf",
        "cashflow_freshness_days",
        "cashflow_quality_schema_v2",
        "cf_nm",
        "cf_sales",
        "cons_analyst_count_30d",
        "cons_analyst_count_chg",
        "cons_eps_dispersion",
        "cons_eps_dispersion_chg",
        "cons_eps_mean_fy0",
        "cons_eps_mean_fy1",
        "cons_eps_mean_fy2",
        "cons_eps_mean_fym1",
        "cons_eps_revision_30d",
        "cons_eps_revision_accel",
        "cons_eps_yield_fy0",
        "cons_eps_yield_fy1",
        "cons_eps_yield_fy2",
        "cons_eps_yield_fym1",
        "cons_rating_score",
        "cons_rating_upgrade_ratio",
        "cons_revision_freshness_days",
        "cons_revision_schema_v2",
        "cons_target_price_mid",
        "cons_target_upside",
        "cons_target_upside_chg",
        "consensus_freshness_days",
        "current_ratio",
        "debt_to_assets",
        "dividend_continuity_5y",
        "dividend_days_to_ex_date",
        "dividend_freshness_days",
        "dividend_growth_3y",
        "dividend_growth_5y",
        "dividend_hist_missing",
        "dividend_payout_ratio",
        "dividend_recent_imp_ann_10d",
        "dividend_schema_v1",
        "dividend_stability_5y",
        "dividend_yield_hist_12m",
        "equity_yoy",
        "express_freshness_days",
        "express_profit_yoy",
        "express_revenue_yoy",
        "express_roe",
        "express_surprise",
        "fcf",
        "fcf_yield",
        "forecast_chg_mid",
        "forecast_freshness_days",
        "forecast_type_score",
        "fundamental_freshness_days",
        "grossprofit_margin",
        "int_to_talcap",
        "inv_turn",
        "netprofit_margin",
        "netprofit_yoy",
        "ocf",
        "ocf_to_profit",
        "ocf_to_revenue",
        "or_yoy",
        "profit_dedt",
        "q_gr_yoy",
        "q_ocf_to_sales",
        "quick_ratio",
        "roa",
        "roe_dt",
        "roe_waa",
    ),
    "moneyflow": (
        "elg_net_amount",
        "elg_net_amount_sum_20",
        "elg_net_amount_sum_5",
        "lg_net_amount",
        "lg_net_amount_sum_20",
        "lg_net_amount_sum_5",
        "lhb_amount_rate",
        "lhb_cont_on_list",
        "lhb_cont_up_days_20",
        "lhb_cont_up_days_5",
        "lhb_net_amount",
        "lhb_net_rate",
        "lhb_net_sum_20",
        "lhb_net_sum_5",
        "lhb_on_list",
        "lhb_reason_count",
        "lhb_up_days_20",
        "margin_net_buy",
        "net_mf_amount",
        "net_mf_amount_mean_20",
        "net_mf_amount_mean_5",
        "net_mf_amount_sum_20",
        "net_mf_amount_sum_5",
        "north_net_buy",
        "north_net_buy_ma20",
        "north_net_buy_ma5",
        "north_net_buy_sign_streak",
        "north_net_buy_sum5",
        "north_net_buy_z20",
        "north_turnover",
        "north_turnover_change_streak",
        "north_turnover_flag",
        "north_turnover_ma20",
        "north_turnover_ma5",
        "north_turnover_sum5",
        "north_turnover_z20",
        "order_imbalance",
        "order_imbalance_mean_20",
        "order_imbalance_mean_5",
        "rqye_rzye_ratio",
        "rzye_chg_20",
        "rzye_chg_5",
        "short_balance_change_5",
        "short_sell_vol_change_5",
    ),
    "technical": (
        "acceleration",
        "alpha_industry_10",
        "alpha_industry_20",
        "alpha_industry_5",
        "amplitude",
        "atr_14",
        "atr_pct_14",
        "bb_lower",
        "bb_middle",
        "bb_pct",
        "bb_upper",
        "bb_width",
        "body_length",
        "cost_concentration",
        "fund_count",
        "fund_count_chg",
        "fund_hold_ratio",
        "fund_hold_ratio_chg",
        "fund_portfolio_freshness_days",
        "ind_momentum_rank",
        "ind_ret_avg",
        "is_new_stock",
        "kdj_d",
        "kdj_j",
        "kdj_k",
        "lower_shadow",
        "macd_dea",
        "macd_dif",
        "macd_hist",
        "rsi_14",
        "size",
        "spec_score",
        "upper_shadow",
        "vol_burst_10",
        "vol_burst_20",
        "vol_burst_5",
        "volatility_10",
        "volatility_20",
        "volatility_5",
        "weight_avg_bias",
        "winner_rate",
        "winner_rate_chg_20",
        "winner_rate_chg_5",
    ),
    "announcement": (
        "block_discount_avg_10d",
        "block_discount_days_10d",
        "days_to_unlock",
        "holder_freshness_days",
        "holder_num_chg",
        "holder_num_chg_2q",
        "pledge_freshness_days",
        "pledge_ratio",
        "pledge_ratio_prev",
        "unlock_ratio",
    ),
    "risk": (
        "amihud_illiq_20",
        "amount_cv_20",
        "cvar_95_20",
        "downside_corr_20",
        "downside_vol_20",
        "drawdown_duration",
        "earnings_yield",
        "gap_risk",
        "garch_persistence",
        "high_low_range_ratio",
        "kurtosis_20",
        "max_drawdown_20",
        "momentum_decay",
        "parkinson_vol_20",
        "pledge_delta",
        "pledge_high_flag",
        "pledge_ratio_decayed",
        "ret_volatility_ratio",
        "skewness_20",
        "turnover_cv_20",
        "turnover_percentile",
        "unlock_risk_flag",
        "up_down_vol_ratio",
        "var_95_20",
        "vol_of_vol_20",
        "vol_ratio_5_20",
        "vol_regime_percentile",
        "volume_climax_days",
        "volume_price_divergence",
    ),
    "market_state": (
        "mkt_adv_dec_ratio",
        "mkt_atr_pct",
        "mkt_atr_pct_ma250",
        "mkt_drawdown_20",
        "mkt_ma250_ratio",
        "mkt_ma_trend",
        "mkt_ret_avg_20",
        "mkt_ret_avg_60",
        "mkt_ret_vol_20",
        "mkt_turnover_ratio",
        "mkt_turnover_std",
        "mkt_vol_20",
        "mkt_vol_cnt",
    ),
    "neutralized": (
        "neu_ret_1",
        "neu_ret_10",
        "neu_ret_20",
        "neu_ret_5",
        "zscore_acceleration",
        "zscore_acceleration_sz",
        "zscore_amount_ma20",
        "zscore_amount_ma20_sz",
        "zscore_assets_turn",
        "zscore_assets_turn_sz",
        "zscore_bb_width",
        "zscore_bb_width_sz",
        "zscore_bp",
        "zscore_bp_sz",
        "zscore_capex_to_ocf",
        "zscore_capex_to_ocf_sz",
        "zscore_cf_nm",
        "zscore_cf_nm_sz",
        "zscore_cf_sales",
        "zscore_cf_sales_sz",
        "zscore_cons_analyst_count_chg",
        "zscore_cons_analyst_count_chg_sz",
        "zscore_cons_eps_dispersion",
        "zscore_cons_eps_dispersion_chg",
        "zscore_cons_eps_dispersion_chg_sz",
        "zscore_cons_eps_dispersion_sz",
        "zscore_cons_eps_revision_accel",
        "zscore_cons_eps_revision_accel_sz",
        "zscore_cons_rating_upgrade_ratio",
        "zscore_cons_rating_upgrade_ratio_sz",
        "zscore_cons_target_upside",
        "zscore_cons_target_upside_chg",
        "zscore_cons_target_upside_chg_sz",
        "zscore_cons_target_upside_sz",
        "zscore_current_ratio",
        "zscore_current_ratio_sz",
        "zscore_debt_to_assets",
        "zscore_debt_to_assets_sz",
        "zscore_dividend_continuity_5y",
        "zscore_dividend_continuity_5y_sz",
        "zscore_dividend_days_to_ex_date",
        "zscore_dividend_days_to_ex_date_sz",
        "zscore_dividend_growth_3y",
        "zscore_dividend_growth_3y_sz",
        "zscore_dividend_growth_5y",
        "zscore_dividend_growth_5y_sz",
        "zscore_dividend_payout_ratio",
        "zscore_dividend_payout_ratio_sz",
        "zscore_dividend_recent_imp_ann_10d",
        "zscore_dividend_recent_imp_ann_10d_sz",
        "zscore_dividend_stability_5y",
        "zscore_dividend_stability_5y_sz",
        "zscore_dividend_yield_hist_12m",
        "zscore_dividend_yield_hist_12m_sz",
        "zscore_dv_ttm",
        "zscore_dv_ttm_sz",
        "zscore_elg_net_amount_sum_20",
        "zscore_elg_net_amount_sum_20_sz",
        "zscore_equity_yoy",
        "zscore_equity_yoy_sz",
        "zscore_fcf_yield",
        "zscore_fcf_yield_sz",
        "zscore_grossprofit_margin",
        "zscore_grossprofit_margin_sz",
        "zscore_int_to_talcap",
        "zscore_int_to_talcap_sz",
        "zscore_intraday_vol_structure",
        "zscore_intraday_vol_structure_sz",
        "zscore_inv_turn",
        "zscore_inv_turn_sz",
        "zscore_log_total_mv",
        "zscore_log_total_mv_sz",
        "zscore_ma_deviation_20",
        "zscore_ma_deviation_20_sz",
        "zscore_macd_hist",
        "zscore_macd_hist_sz",
        "zscore_net_mf_amount",
        "zscore_net_mf_amount_sz",
        "zscore_netprofit_margin",
        "zscore_netprofit_margin_sz",
        "zscore_netprofit_yoy",
        "zscore_netprofit_yoy_sz",
        "zscore_ocf_to_profit",
        "zscore_ocf_to_profit_sz",
        "zscore_ocf_to_revenue",
        "zscore_ocf_to_revenue_sz",
        "zscore_opening_strength",
        "zscore_opening_strength_sz",
        "zscore_or_yoy",
        "zscore_or_yoy_sz",
        "zscore_order_imbalance",
        "zscore_order_imbalance_sz",
        "zscore_pb",
        "zscore_pb_sz",
        "zscore_pe_ttm",
        "zscore_pe_ttm_sz",
        "zscore_profit_dedt",
        "zscore_profit_dedt_sz",
        "zscore_q_gr_yoy",
        "zscore_q_gr_yoy_sz",
        "zscore_quick_ratio",
        "zscore_quick_ratio_sz",
        "zscore_roa",
        "zscore_roa_sz",
        "zscore_roe_dt",
        "zscore_roe_dt_sz",
        "zscore_roe_waa",
        "zscore_roe_waa_sz",
        "zscore_size",
        "zscore_turnover_rate",
        "zscore_turnover_rate_sz",
        "zscore_volatility_10",
        "zscore_volatility_10_sz",
        "zscore_volatility_20",
        "zscore_volatility_20_sz",
        "zscore_volatility_5",
        "zscore_volatility_5_sz",
    ),
}

#: 物化派生列（冻结 §6；全部进 announcement 族，status=deprecated）
MATERIALIZED_DERIVED: dict[str, tuple[str, ...]] = {
    "ht": (
        "ht_net_ratio_30d",
        "ht_net_ratio_90d",
        "ht_net_ratio_30d_exec",
        "ht_net_ratio_30d_other",
        "ht_buy_count_30d",
        "ht_sell_count_30d",
        "ht_net_count_90d",
        "ht_net_ratio_accel",
        "ht_freshness_days",
        "holdertrade_schema_v1",
    ),
    "rp": (
        "rp_amount_to_mv_90d",
        "rp_amount_to_mv_180d",
        "rp_exec_flag_90d",
        "rp_price_headroom",
        "rp_freshness_days",
        "repurchase_schema_v1",
    ),
    "tfh": (
        "tfh_top10_ratio",
        "tfh_top1_ratio",
        "tfh_inst_ratio",
        "tfh_inst_count",
        "tfh_social_security_flag",
        "tfh_concentration_chg",
        "tfh_freshness_days",
        "tfh_schema_v1",
    ),
    "ti": (
        "ti_inst_net_ratio",
        "ti_inst_buy_ratio",
        "ti_inst_sell_ratio",
        "ti_inst_net_sum_20",
        "ti_inst_days_20",
        "ti_schema_v1",
    ),
    "has": (
        "has_cons_coverage",
        "has_margin_balance",
        "has_fund_holding",
        "has_express_data",
    ),
}

#: 标签表 → (label 值列, neu 变体列)（labels 独立成表，不是 panel 族）
LABEL_TABLES: dict[str, tuple[str, str]] = {
    "y_ret_5": ("y_ret_5", "neu_y_ret_5"),
    "y_ret_10": ("y_ret_10", "neu_y_ret_10"),
    "y_ret_20": ("y_ret_20", "neu_y_ret_20"),
}

#: 全部标签列（6 个；大表剥离标签用）
LABEL_VALUE_COLUMNS: tuple[str, ...] = tuple(c for pair in LABEL_TABLES.values() for c in pair)

#: 物化列 → announcement 族（扁平化）
MATERIALIZED_COLUMNS: tuple[str, ...] = tuple(
    c for cols in MATERIALIZED_DERIVED.values() for c in cols
)


def group_of_column(col: str) -> str:
    """列所属 panel 族（物化列归 announcement）。未登记列 ⇒ KeyError。"""
    for group, cols in PANEL_GROUPS.items():
        if col in cols:
            return group
    if col in MATERIALIZED_COLUMNS:
        return "announcement"
    raise KeyError(f"列未登记于 v2 列族分组表: {col!r}")


def columns_of_group(group: str) -> tuple[str, ...]:
    """族的全部列（announcement = 10 基础列 + 34 物化列）。未知族 ⇒ KeyError。"""
    if group not in PANEL_GROUPS:
        raise KeyError(f"未知 panel 族: {group!r}（合法值 {sorted(PANEL_GROUPS)}）")
    if group == "announcement":
        return PANEL_GROUPS[group] + MATERIALIZED_COLUMNS
    return PANEL_GROUPS[group]


def validate_mapping() -> None:
    """映射完备性断言：383+34 无重复；PANEL_GROUPS 并集 == 383−labels 6 == 377。

    失败 ⇒ ValueError（本函数在模块测试与 bootstrap 前各跑一次，防手工改表出错）。
    """
    panel_cols = [c for cols in PANEL_GROUPS.values() for c in cols]
    if len(panel_cols) != 377:
        raise ValueError(f"PANEL_GROUPS 并集列数 {len(panel_cols)} != 377（383−labels 6）")
    all_cols = panel_cols + list(MATERIALIZED_COLUMNS)
    if len(all_cols) != len(set(all_cols)):
        dupes = sorted({c for c in all_cols if all_cols.count(c) > 1})
        raise ValueError(f"列族分组表存在重复列: {dupes}")
    if len(MATERIALIZED_COLUMNS) != 34:
        raise ValueError(f"物化派生列数 {len(MATERIALIZED_COLUMNS)} != 34")
    label_overlap = set(LABEL_VALUE_COLUMNS) & set(all_cols)
    if label_overlap:
        raise ValueError(f"标签列混入 panel 族: {sorted(label_overlap)}")
